name: github pages

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '5.02.x'
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam pin -n .

      - run: opam depext -yt bare

      - run: opam install -d . --deps-only

      - run: opam exec -- dune build @doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html/
          destination_dir: .
          enable_jekyll: false
